### ISSUE TITLE
Errors regarding --combine-consensus

### ISSUE THREAD

**Issue by hd00ljy** [fritzsedlazeck/Sniffles#300]
I found two errors while testing the multi-sample calling with --combine-consensus option.

1. Command
```
${SNIFFLES} \
 --combine-null-min-coverage 4 \
 --combine-output-filtered \
 --combine-consensus \
 --input $dirs_tmp \
 --vcf ${output}_consensus.vcf \
 --tandem-repeats ${tandemrepeats} \
 --reference ${ref} \
 --minsupport $th \
 --output-rnames \
 -t $thread \
 --mapq ${mapqualth}  \
 --phase
```

1. Error1
I got the following error message
```
Calling SVs across 1 samples (70037666 candidates total)...

Process Process-2:
Traceback (most recent call last):
  File "/home/hd00ljy/.conda/envs/sniffles2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/hd00ljy/.conda/envs/sniffles2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hd00ljy/.conda/envs/sniffles2/lib/python3.9/site-packages/sniffles/parallel.py", line 196, in Main
    raise e
  File "/home/hd00ljy/.conda/envs/sniffles2/lib/python3.9/site-packages/sniffles/parallel.py", line 193, in Main
    Main_Internal(proc_id,config,pipe)
  File "/home/hd00ljy/.conda/envs/sniffles2/lib/python3.9/site-packages/sniffles/parallel.py", line 327, in Main_Internal
    result["svcalls"],candidates_processed=task.combine(config)
  File "/home/hd00ljy/.conda/envs/sniffles2/lib/python3.9/site-packages/sniffles/parallel.py", line 169, in combine
    svcalls.extend(sv.call_groups(groups_call,config,self))
  File "/home/hd00ljy/.conda/envs/sniffles2/lib/python3.9/site-packages/sniffles/sv.py", line 224, in call_groups
    svcall=call_group(group,config,task)
  File "/home/hd00ljy/.conda/envs/sniffles2/lib/python3.9/site-packages/sniffles/sv.py", line 283, in call_group
    for a,b,gt_qual,dr,dv in genotypes.values(): ###
ValueError: too many values to unpack (expected 5)
Sniffles2 Error: An exception occured in a worker process (see surrounding error messages) (Fatal error, exiting.)
Sniffles2Main: Shutting down workers
```

This part of the sv.py was problematic
![image](https://user-images.githubusercontent.com/13775022/157886165-d37c9c32-15e2-40bb-b771-3e2726a5eee1.png)

The problem seems that the values of the genotypes dict contain some IDs as its 6th elements

I temporarily fixed it by changing it to the following.
```
for a,b,gt_qual,dr,dv,_ in genotypes.values():
```

3. Error2
After fixing that one I encountered another error.

```
Traceback (most recent call last):
  File "/home/hd00ljy/.conda/envs/sniffles2/lib/python3.9/site-packages/sniffles/sv.py", line 292, in call_group
    cons_a,cons_b=max(most_common_gt)
TypeError: '>' not supported between instances of 'str' and 'int'
```

I checked the most_common_gt  that gave error and found that it contained '.' as a and b.

```
>>> print(most_common_gt)
[(0, 1), ('.', '.')]
```

Could you check on these errors?

**Comment by smolkmo** [comment]
Hi hd00ljy,

thanks for pointing this out and sorry for the delay.

The genotype consensus mode is an experimental additional feature that in merging, instead of outputting genotypes separately for each sample, outputs only a single genotype column containing the most common genotype across all the samples.

Just to be sure, may I ask if this is also your intention in merging?

Best,
Moritz

**Comment by hd00ljy** [comment]
Hi Moritz!

Thank you for the detailed response!

I actually have no intention in merging if the option is for reporting the most frequant genotype.

I  am just trying out new features of the sniffles to see if they are useful to my study.

With regards,
Jin-Young
