### ISSUE TITLE
Force calling

### ISSUE THREAD

**Issue by Akazhiel** [fritzsedlazeck/Sniffles#306]
Hello!

I'm trying to force call SVs found with another variant caller using sniffles but every time I try running it I get this error:

```
Traceback (most recent call last):
  File "/opt/conda/envs/Nanopore_WGS/bin/sniffles", line 607, in <module>
    Sniffles2_Main(config.from_cmdline(),processes)
  File "/opt/conda/envs/Nanopore_WGS/bin/sniffles", line 575, in Sniffles2_Main
    vcf_out.rewrite_genotype(genotype_lineindex_svcalls_returned[lineindex])
  File "/opt/conda/envs/Nanopore_WGS/lib/python3.7/site-packages/sniffles/vcf.py", line 307, in rewrite_genotype
    parts=parts_no_gt + [gt_format,format_genotype(gt)]
  File "/opt/conda/envs/Nanopore_WGS/lib/python3.7/site-packages/sniffles/vcf.py", line 36, in format_genotype
    a,b,qual,dr,dv,ps,id=gt
ValueError: not enough values to unpack (expected 7, got 5)
```

Also for some reason it wipes out completely the input vcf that has to be re-genotyped.

Edit: Wiping out the input vcf was a mistake on my part I didn't notice as I was using the same file as input and output.

Best regards,

Jonatan

**Comment by smolkmo** [comment]
Hi Jonatan,

thanks for your report!
we were able to reproduce and fix the force calling problem described by you - you can switch to the new version using `pip install sniffles==2.0.6` . We also introduced disallowing using existing files as output by default.

Hope this helps and best regards,
Moritz
