### ISSUE TITLE
Error when reading SNF header from files

### ISSUE THREAD

**Issue by mpalmada** [fritzsedlazeck/Sniffles#335]
Dear Fritz Sedlazeck,

I am trying to run the Multi-sample calling with Sniffles v2.0.2 and I get an error in the second step. I run it like this:

sniffles --minsupport 10 -t 4 --minsvlen 10 --input ${bam} --snf ${snf}

I get snf files and then I create a tsv with the files list.

Finally I run:

sniffles --input ${tsv} --vcf ${vcf}

And get the following error:

Error when reading SNF header from 'SAMPLE1_sniffles_snf.snf': Expecting value: line 1 column 1 (char 0). The file may not be a valid .snf file or could have been corrupted.
Traceback (most recent call last):
  File "/home/devel/mpalmada/.conda/envs/sniffles2/bin/sniffles", line 607, in <module>
    Sniffles2_Main(config.from_cmdline(),processes)
  File "/home/devel/mpalmada/.conda/envs/sniffles2/bin/sniffles", line 312, in Sniffles2_Main
    snf_in.read_header()
  File "/home/devel/mpalmada/.conda/envs/sniffles2/lib/python3.9/site-packages/sniffles/snf.py", line 96, in read_header
    raise e
  File "/home/devel/mpalmada/.conda/envs/sniffles2/lib/python3.9/site-packages/sniffles/snf.py", line 93, in read_header
    self.header=json.loads(header_text.strip())
  File "/home/devel/mpalmada/.conda/envs/sniffles2/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/devel/mpalmada/.conda/envs/sniffles2/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/devel/mpalmada/.conda/envs/sniffles2/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Do you have any idea of what is happening? Hope you can help me on this!

Thanks a lot!

Sincerely,

Marc

**Comment by fritzsedlazeck** [comment]
Sorry @mpalmada for the late reply. 

Can you confirm that the first step ran successfully? If so please also let us know if the path to the file is correct. 
We have tested this step over multiple thousands of genomes and it seems to be very robust. 

Please let us know
Thanks
Fritz
