### ISSUE TITLE
error appear when force calling

### ISSUE THREAD

**Issue by maxineliu** [fritzsedlazeck/Sniffles#344]
Hi,
I have completed multiple samples SV calling to generate a VCF across 12 samples -- `12bufo.vcf`. Then I would like to run force calling to genotype every individual. However, error message appeared. 
```
Running Sniffles2, build 2.0.7
  Run Mode: genotype_vcf
  Start on: 2022/07/28 17:44:15
  Working dir: /home/maxine91
  Used command: /home/maxine91/p39_sniffles2.0.7/bin/sniffles --input /home/maxine91/projects/def-jfu/results/minimap2_bufo.dir/aln.sorted.cy201704.bam --genotype-vcf /home/maxine91/scratch/sniffles.dir/12bufo.vcf --vcf cy201704.force.207.vcf
==============================
Opening for reading: /home/maxine91/projects/def-jfu/results/minimap2_bufo.dir/aln.sorted.cy201704.bam
Opening for reading: /home/maxine91/scratch/sniffles.dir/12bufo.vcf (read 3036302 SVs to be genotyped)
Opening for writing: cy201704.force.207.vcf (single-sample, sorted)

Analyzing 54731758 alignments total...

 3451783/54731758 alignments processed (6%, 1547/s); 738/748 tasks done; parallel 4/4; 
 7010803/54731758 alignments processed (12%, 2862/s); 740/748 tasks done; parallel 4/4; 
 9316739/54731758 alignments processed (17%, 3516/s); 741/748 tasks done; parallel 4/4; 
Traceback (most recent call last):
  File "/home/maxine91/p39_sniffles2.0.7/bin/sniffles", line 616, in <module>
    Sniffles2_Main(config.from_cmdline(),processes)
  File "/home/maxine91/p39_sniffles2.0.7/bin/sniffles", line 452, in Sniffles2_Main
    command,result=proc.pipe_main.recv()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.9.6/lib/python3.9/multiprocessing/connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.9.6/lib/python3.9/multiprocessing/connection.py", line 426, in _recv_bytes
    return self._recv(size)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.9.6/lib/python3.9/multiprocessing/connection.py", line 390, in _recv
    raise OSError("got end of file during message")
OSError: got end of file during message
```

Here are something needed to be mentioned:
1. The length of chromosome for my samples is longer than 2^29 bases, so the indexes of aligned bam files are stored in csi format;
2. According to [issue 317](https://github.com/fritzsedlazeck/Sniffles/issues/317#issuecomment-1118245931), I also modify the code in version 2.0.7.

Why did this error happen? How can I resolve this problem? Thanks in advance!

Maxine

**Comment by maxineliu** [comment]
The problem is solved after increasing the memory. I'll close this issue.
