### ISSUE TITLE
trouble processing minimap alignments from guppy

### ISSUE THREAD

**Issue by RichardCorbett** [fritzsedlazeck/Sniffles#349]
Hi there.

I am using guppy to basecall my ONT data and recently I started testing the option for it to create a bam that contains methylation data.

The bam I created contains 30X whole genome GM24385 ONT  reads aligned to hg38.

Using an older sniffles version (1_0_12b) and this command:
`/gsc/software/linux-x86_64-centos7/sniffles-1.0.12b/bin/sniffles-core-1.0.12/sniffles -m F16406.sorted_hg38.bam -t 48 -v sniffles_1_0_12b_F16406.sorted_hg38.bam.vcf`
I get this error:
`Too few reads detected in F16406.sorted_hg38.bam`
I did some googling suggesting the error could be that I am missing NM tags.  I can confirm that there are NM tags in my bam, but not for all reads.  Could that be the issue?

I also tested using a much more contemporary  release (2.0.7).
Command:
`sniffles -i  F16406.sorted_hg38.bam  -v F16406.sorted_hg38.bam.vcf  --allow-overwrite`
which generated the following output
```
Running Sniffles2, build 2.0.7
  Run Mode: call_sample
  Start on: 2022/08/15 09:29:30
  Working dir: work/21/00b05dc967826a4aec32cac0ec0055
  Used command: /home/rcorbett/miniconda3/envs/sniffles/bin/sniffles -i F16406.sorted_hg38.bam -v F16406.sorted_hg38.bam.vcf --allow-overwrite
==============================
Opening for reading: F16406.sorted_hg38.bam
[W::hts_idx_load3] The index file is older than the data file: F16406.sorted_hg38.bam.bai
Opening for writing: F16406.sorted_hg38.bam.vcf (single-sample, sorted)

Analyzing 3990634 alignments total...

[W::hts_idx_load3] The index file is older than the data file: F16406.sorted_hg38.bam.bai
[W::hts_idx_load3] The index file is older than the data file: F16406.sorted_hg38.bam.bai
[W::hts_idx_load3] The index file is older than the data file: F16406.sorted_hg38.bam.bai
[W::hts_idx_load3] The index file is older than the data file: F16406.sorted_hg38.bam.bai
Process Process-4:
Traceback (most recent call last):
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/site-packages/sniffles/parallel.py", line 196, in Main
    raise e
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/site-packages/sniffles/parallel.py", line 193, in Main
    Main_Internal(proc_id,config,pipe)
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/site-packages/sniffles/parallel.py", line 212, in Main_Internal
    _,read_count=task.build_leadtab(config)
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/site-packages/sniffles/parallel.py", line 42, in build_leadtab
    externals=self.lead_provider.build_leadtab(self.contig,self.start,self.end,self.bam)
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/site-packages/sniffles/leadprov.py", line 488, in build_leadtab
    for ld in self.iter_region(bam,contig,start,end):
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/site-packages/sniffles/leadprov.py", line 543, in iter_region
    for lead in read_iterindels(curr_read_id,read,contig,self.config,use_clips,read_nm=nm):
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/site-packages/sniffles/leadprov.py", line 182, in read_iterindels
    seq=read.query_sequence[pos_read:pos_read+oplength] if oplength <= seq_cache_maxlen else None)
TypeError: 'NoneType' object is not subscriptable
Sniffles2 Error: An exception occured in a worker process (see surrounding error messages) (Fatal error, exiting.)
Sniffles2Main: Shutting down workers
Process Process-3:
Traceback (most recent call last):
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/site-packages/sniffles/parallel.py", line 196, in Main
    raise e
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/site-packages/sniffles/parallel.py", line 193, in Main
    Main_Internal(proc_id,config,pipe)
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/site-packages/sniffles/parallel.py", line 212, in Main_Internal
    _,read_count=task.build_leadtab(config)
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/site-packages/sniffles/parallel.py", line 42, in build_leadtab
    externals=self.lead_provider.build_leadtab(self.contig,self.start,self.end,self.bam)
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/site-packages/sniffles/leadprov.py", line 488, in build_leadtab
    for ld in self.iter_region(bam,contig,start,end):
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/site-packages/sniffles/leadprov.py", line 543, in iter_region
    for lead in read_iterindels(curr_read_id,read,contig,self.config,use_clips,read_nm=nm):
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/site-packages/sniffles/leadprov.py", line 182, in read_iterindels
    seq=read.query_sequence[pos_read:pos_read+oplength] if oplength <= seq_cache_maxlen else None)
TypeError: 'NoneType' object is not subscriptable
Process Process-2:
Traceback (most recent call last):
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/site-packages/sniffles/parallel.py", line 196, in Main
    raise e
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/site-packages/sniffles/parallel.py", line 193, in Main
    Main_Internal(proc_id,config,pipe)
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/site-packages/sniffles/parallel.py", line 212, in Main_Internal
    _,read_count=task.build_leadtab(config)
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/site-packages/sniffles/parallel.py", line 42, in build_leadtab
    externals=self.lead_provider.build_leadtab(self.contig,self.start,self.end,self.bam)
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/site-packages/sniffles/leadprov.py", line 488, in build_leadtab
    for ld in self.iter_region(bam,contig,start,end):
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/site-packages/sniffles/leadprov.py", line 543, in iter_region
    for lead in read_iterindels(curr_read_id,read,contig,self.config,use_clips,read_nm=nm):
  File "/home/rcorbett/miniconda3/envs/sniffles/lib/python3.10/site-packages/sniffles/leadprov.py", line 182, in read_iterindels
    seq=read.query_sequence[pos_read:pos_read+oplength] if oplength <= seq_cache_maxlen else None)
TypeError: 'NoneType' object is not subscriptable
```
 Is there anything I can check to try and figure out what is going wrong?

**Comment by fritzsedlazeck** [comment]
Dear Richard,
the sniffles2 error points more to that there is some dates on index vs. bam file that is out of order. So I would check that first.  "The index file is older than the data file: F16406.sorted_hg38.bam.bai" 

I have not worked personally with a guppy bam file. I remember that megladon didn't report split reads which meant that SV weren't called (rearrangements mainly). So please keep an eye out for that. 

hope that helps
Fritz

**Comment by RichardCorbett** [comment]
Thanks for the speedy reply!

Regarding split reads I have the following flagstats suggesting that the guppy minimap alignment includes both supplementary and secondary alignments.  Are these the type of split reads you are thinking of?


  | Minimap outside guppy (hg38) | Guppy alignments (hg19) | Guppy alignments (hg38)
-- | -- | -- | --
in total | 13873124 | 12302068 | 12317360
secondary | 3004994 | 2608524 | 2729620
supplementary | 884322 | 608266 | 502462
mapped | 13758666 | 12288850 | 12226494
calculated total reads from above | 9983808 | 9085278 | 9085278
size of BAM (hg38) | 185Gb | 114Gb | 113Gb

I also re-created my `.bai` file to ensure it is newer than my bam and got the same error as above with both versions of sniffles.    Is there anything else I should check for?

**Comment by fritzsedlazeck** [comment]
Thats great.
Can you load that bam file in IGV? (I assume indexing went ok ?) 
If all of this doesn't help you can of course share the bam with me/us and we can take a look. It must be something quite obvious because otherwise other people would have the same issue.
Thx
Fritz

**Comment by RichardCorbett** [comment]
I'm looking for some differences in the bams and was surprised to find that the guppy minimap bam doesn't contain either the read sequence or the read quality string.   The only long strings listed per read are the MD tag and the CIGAR string.  As shown above the guppy bams are much smaller than the standalone minimap, so this seems to line up as expected.

I wouldn't be surprised if the lack of the read sequence would cause issues for a reasonable SV caller like sniffles, but could you confirm?

**Comment by fritzsedlazeck** [comment]
We are for sure using the read sequence. Sorry I missed that fact and digesting the table.... 
 Maybe we can give a better error msg @smolkmo ?
Thanks
Fritz

**Comment by RichardCorbett** [comment]
Example read pulled from a standalone minimap2 alignment:
```
f9f1c773-379a-400b-8ba6-680e75efde98	272	1	340778	0	3725S88M[truncated for brevity]     *	0	0	TTGTTACGTATTGC[truncated for brevity]       	%$#%&&&&&&*212**.7889; [truncated for brevity].       	RG:Z:272420_fastq_runid_1a9f7de9b4571f6bc9d6ff2d9713f9815f79e33NM:i:763	ms:i:26382	AS:i:26385	nn:i:0	tp:A:S	cm:i:1575	s1:i:10926	de:f:0.0371	MD:Z:88^[truncated for brevity]
```
and from the guppy minimap2 module:
```
f9f1c773-379a-400b-8ba6-680e75efde98	272	1	340778	0	3669S95M3I1[truncated for brevity]	*	0	18971	*	*	AS:i:25057	MD:Z:7T106^[truncated for brevity]
```

Sorry causing the distraction on this one.  I'll see if the folks at ONT can change this.

**Comment by fritzsedlazeck** [comment]
Thanks Richard, 
let me know what you find out. 
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Dear Richard, 
this is very fresh, but apparently, if you use --moves_out on guppy the sequence and base qualities are kept. We haven't tested this yet and its clearly not intended.. but seems that the bam file is ok with that parameter.. 
Cheers
Fritz

**Comment by fritzsedlazeck** [comment]
Oh didnt work...

**Comment by RichardCorbett** [comment]
Thats too bad.  I was away last week and read your first message this morning so I set up a test myself that is waiting on the cluster and then I saw that you mentioned it didn't work.   Thanks for the heads up though.  I've had some back and forth with our nanopore FAS who tells me this is something nanopore are working on (take this with an appropriately tasty grain of salt).

**Comment by fritzsedlazeck** [comment]
So we did a bit more digging. You can filter out supplement alignments and then it apparently should work..  "samtools view -F 0x800"  .. I have already reached out to ONT so they hopefully fix that behaviour. 
Please let me know if that works since I haven't tested it myself. 
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Here is what ONT just released: https://community.nanoporetech.com/posts/guppy-6-3-7-release
