### ISSUE TITLE
no attribute error

### ISSUE THREAD

**Issue by iremdnzl** [fritzsedlazeck/Sniffles#365]
Hi,
I'm having this following error:
`Traceback (most recent call last):
  File "/home/analysispc/anaconda3/bin/sniffles", line 33, in <module>
    from sniffles import parallel
  File "/home/analysispc/anaconda3/lib/python3.9/site-packages/sniffles/parallel.py", line 17, in <module>
    from sniffles import leadprov
  File "/home/analysispc/anaconda3/lib/python3.9/site-packages/sniffles/leadprov.py", line 137, in <module>
    OPTAB={pysam.CMATCH:     (1,1,0),
AttributeError: module 'pysam' has no attribute 'CMATCH'`
What should I do?

**Comment by fritzsedlazeck** [comment]
Could you check please the version of pysam you have installed? 
Did you try a pip install or a conda installation or is that directly from github ? 
Thanks
Fritz
