### ISSUE TITLE
Public pacbio bams have no SEQ lines.. how to format so that sniffles will take it?

### ISSUE THREAD

**Issue by jamesdalg** [fritzsedlazeck/Sniffles#393]
Hello!

I'm writing up a pipeline for SV calling, using public pacbio data (from https://downloads.pacbcloud.com/public/revio/2022Q4/), but there are unfortunately no @SEQ lines in the header. What is the best practice to get this fixed so I can use sniffles to call the SVs? I did some digging and found the proper fasta file that it was aligned to is found in this vignette from deepVariant: https://github.com/google/deepvariant/blob/ab068c4588a02e2167051bd9e74c0c9579462b51/docs/deeptrio-pacbio-case-study.md.

Best,
James Dalgleish

Below is my command, output, and the public bam header.

```
/ceph/project/davieslab/jdalglei/code/sm/snakemake-pacbio$ sniffles --input /ceph/project/davieslab/jdalglei/data/pacbio/bam/HG004_rep1.bam --vcf /project/davieslab/jdalglei/results/sm_pacbio/HG004_rep1/sniffles/HG004_rep1_sniffles.vcf --threads 1 --snf /project/davieslab/jdalglei/results/sm_pacbio/HG004_rep1/sniffles/HG004_rep1.snf
Running Sniffles2, build 2.0.7
  Run Mode: call_sample
  Start on: 2023/04/24 12:02:14
  Working dir: /ceph/project/davieslab/jdalglei/code/sm/snakemake-pacbio
  Used command: /Filers/home/j/jdalglei/mambaforge/bin/sniffles --input /ceph/project/davieslab/jdalglei/data/pacbio/bam/HG004_rep1.bam --vcf /project/davieslab/jdalglei/results/sm_pacbio/HG004_rep1/sniffles/HG004_rep1_sniffles.vcf --threads 1 --snf /project/davieslab/jdalglei/results/sm_pacbio/HG004_rep1/sniffles/HG004_rep1.snf
==============================
Opening for reading: /ceph/project/davieslab/jdalglei/data/pacbio/bam/HG004_rep1.bam
Traceback (most recent call last):
  File "/Filers/home/j/jdalglei/mambaforge/bin/sniffles", line 616, in <module>
    Sniffles2_Main(config.from_cmdline(),processes)
  File "/Filers/home/j/jdalglei/mambaforge/bin/sniffles", line 118, in Sniffles2_Main
    bam_in=pysam.AlignmentFile(config.input, config.input_mode)
  File "pysam/libcalignmentfile.pyx", line 747, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 996, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False
/ceph/project/davieslab/jdalglei/code/sm/snakemake-pacbio$ samtools view -H /ceph/project/davieslab/jdalglei/data/pacbio/bam/HG004_rep1.bam
@HD	VN:1.6	SO:unknown	pb:5.0.0
@RG	ID:78e84bf7	PL:PACBIO	DS:READTYPE=CCS;Ipd:Frames=ip;PulseWidth:Frames=pw;BINDINGKIT=102-739-100;SEQUENCINGKIT=102-118-800;BASECALLERVERSION=5.0;FRAMERATEHZ=100.000000	LB:HG004-rep1	SM:HG004	PU:m84010_220919_232145_s1	CM:R/P1-C1/5.0-25M
@PG	ID:ccs	PN:ccs	VN:6.99.99 (commit v6.5.0-62-g11dde624)	DS:Generate circular consensus sequences (ccs) from subreads.	CL:ccs m84010_220919_232145_s1.subreads.bam m84010_220919_232145_s1.hifi_reads.bam --knrt-ada --log-level INFO --pbdc-model exp44744216_wu_1-c101-fixed2048.onnx --gpu-80g-40g --pbdc-gpu-devices 0,0,0,0,1,1,2,2,2,2,3,3,3,3
@PG	ID:primrose	VN:1.3.99 (commit v1.3.0-7-g2b7d465)	CL:primrose m84010_220919_232145_s1.hifi_reads.bam 5mC/m84010_220919_232145_s1.hifi_reads.bam --log-level INFO
@PG	ID:samtools	PN:samtools	PP:primrose	VN:1.16.1	CL:samtools view -H /ceph/project/davieslab/jdalglei/data/pacbio/bam/HG004_rep1.bam

```

**Comment by MeHelmy** [comment]
Hi @jamesdalg,

I wanted to inquire if you have downloaded the file "https://downloads.pacbcloud.com/public/revio/2022Q4/HG004-rep1/m84010_220919_232145_s1.hifi_reads.bam" and utilized it as an input for Sniffles?

Thank you,
Medhat

**Comment by jamesdalg** [comment]
I actually did fix this, but I cannot remember how exactly how I did this.
