### ISSUE TITLE
My BAM file is intact

### ISSUE THREAD

**Issue by Qiutaxx** [fritzsedlazeck/Sniffles#450]
(sniffles) [qiutaixing@master cnnLSV]$ sniffles -i HG00512_bwamem_GRCh38DH_CHS_20160905_pacbio.bam -v HG00512_sniffles.vcf
Running Sniffles2, build 2.2
  Run Mode: call_sample
  Start on: 2024/01/11 16:01:05
  Working dir: /home/qiutaixing/cnnLSV
  Used command: /home/qiutaixing/.conda/envs/sniffles/bin/sniffles -i HG00512_bwamem_GRCh38DH_CHS_20160905_pacbio.bam -v HG00512_sniffles.vcf
==============================
Opening for reading: HG00512_bwamem_GRCh38DH_CHS_20160905_pacbio.bam
Opening for writing: HG00512_sniffles.vcf (single-sample, sorted)

Analyzing 8493306 alignments total...

[E::bgzf_read] Read block operation failed with error 33 after 0 of 4 bytes
Process Process-2:
Traceback (most recent call last):
  File "/home/qiutaixing/.conda/envs/sniffles/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/qiutaixing/.conda/envs/sniffles/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/qiutaixing/.conda/envs/sniffles/lib/python3.7/site-packages/sniffles/parallel.py", line 218, in Main
    raise e
  File "/home/qiutaixing/.conda/envs/sniffles/lib/python3.7/site-packages/sniffles/parallel.py", line 215, in Main
    Main_Internal(proc_id,config,pipe)
  File "/home/qiutaixing/.conda/envs/sniffles/lib/python3.7/site-packages/sniffles/parallel.py", line 234, in Main_Internal
    _,read_count=task.build_leadtab(config)
  File "/home/qiutaixing/.conda/envs/sniffles/lib/python3.7/site-packages/sniffles/parallel.py", line 42, in build_leadtab
    externals=self.lead_provider.build_leadtab(self.contig,self.start,self.end,self.bam)
  File "/home/qiutaixing/.conda/envs/sniffles/lib/python3.7/site-packages/sniffles/leadprov.py", line 541, in build_leadtab
    for ld in self.iter_region(bam,contig,start,end):
  File "/home/qiutaixing/.conda/envs/sniffles/lib/python3.7/site-packages/sniffles/leadprov.py", line 571, in iter_region
    for read in bam.fetch(contig,start,end,until_eof=False):
  File "pysam/libcalignmentfile.pyx", line 2094, in pysam.libcalignmentfile.IteratorRowRegion.__next__
OSError: truncated file
Sniffles2 Error: An exception occured in a worker process (see surrounding error messages) (Fatal error, exiting.)
Sniffles2Main: Shutting down workers

My BAM file is intact

**Comment by fritzsedlazeck** [comment]
Dear Qiutaxx,
can you check if e.g. IGV or samtools can index that bam file correctly ? 
While you can use bwa mem of pacbio reads, I would suggest you look into minimap2 or NGMLR or another long read optimized mapper. That should provide a better mapping to the reference. 
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Closing this as we didnt get much response..
