### ISSUE TITLE
v2.3.2 error

### ISSUE THREAD

**Issue by weishwu** [fritzsedlazeck/Sniffles#474]
I got this error when using `quay.io/biocontainers/sniffles:2.3.2--pyhdfd78af_1`.

```
2024-04-18 19:18:08,815 ERROR sniffles.worker (65811): Unhandled error in worker 0. This may result in an orphened worker process.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sniffles/parallel.py", line 517, in run_parent
    self.maybe_recycle()
  File "/usr/local/lib/python3.10/site-packages/sniffles/parallel.py", line 494, in maybe_recycle
    recycle = self.recycle(self.id, self.process.pid) if callable(self.recycle) else self.recycle
  File "/usr/local/lib/python3.10/site-packages/sniffles/utils/resmon.py", line 137, in __call__
    if worker_pid in self._workers:
AttributeError: 'ResourceMonitor' object has no attribute '_workers'
2024-04-18 19:18:08,816 INFO sniffles.worker (65811): Starting worker 1
2024-04-18 19:18:08,818 ERROR sniffles.worker (65811): Unhandled error in worker 1. This may result in an orphened worker process.
```

I see that there is already a post about it. This post can be closed.

**Comment by lfpaulin** [comment]
Hello @weishwu 
It looks like you are using the `--mosaic` tag which will only report SV with a variant allele frequency (VAF) between 5-20% and the SV you show look like "germline". Could you try to re-run without that parameter and see if the SV is detected

Best,
Luis

**Comment by weishwu** [comment]
@lfpaulin I just realized it was because the run failed with the error that seems to be specific to v2.3.2. I rolled back to v2.2 and the DEL was called.
Thanks for telling me that `mosaic` only reports VAF between 5-20%. So I will need to run the germline mode to get >20%, am I right? Is there a way to get <5%?

**Comment by lfpaulin** [comment]
@weishwu could you please share the error message from 2.3.2 please so we can fix it
without the `--mosaic` flag you will get SV with VAF >20%
to get SV with VAF < 5% you need to use: `--mosaic ---mosaic-af-min ${VALUE}" where the VALUE < 0.05

**Comment by weishwu** [comment]
@lfpaulin Thanks!
