### ISSUE TITLE
vcf_out may be unbound in sniffles v2.3.2

### ISSUE THREAD

**Issue by MikkelSchubert** [fritzsedlazeck/Sniffles#476]
If `--vcf` is not set on the command-line, then the `vcf_out` variable is unbound at
https://github.com/fritzsedlazeck/Sniffles/blob/d2d3bfd656332a46686d1e65a388a2145cca4052/src/sniffles/sniffles#L447

I'm guessing that the fix is just to add `vcf_out = None` before
https://github.com/fritzsedlazeck/Sniffles/blob/d2d3bfd656332a46686d1e65a388a2145cca4052/src/sniffles/sniffles#L190

Output:

    2024-04-22 13:02:36,811 INFO sniffles.main (1575379): Used command: sniffles --threads 8 --reference resources/genome.fa --input input.bam --snf output.snf --tandem-repeats human_GRCh38_no_alt_analysis_set.trf.bed
    [snip]
    2024-04-22 13:04:29,601 INFO sniffles.main (1575379): Took 110.51s.
    2024-04-22 13:04:29,601 INFO sniffles.main (1575379): 
    Traceback (most recent call last):
      File "/opt/software/sniffles/2.3.2/bin/sniffles", line 511, in <module>
        Sniffles2_Main(processes)
      File "/opt/software/sniffles/2.3.2/bin/sniffles", line 447, in Sniffles2_Main
        t.result.emit(vcf_out=vcf_out, snf_out=snf_out, **rkwargs)
    UnboundLocalError: cannot access local variable 'vcf_out' where it is not associated with a value

**Comment by hermannromanek** [comment]
Hi @MikkelSchubert ,

Thanks for reporting this, you are right - I just pushed a fix containing your suggestion.

Thanks,
Hermann

**Comment by lfpaulin** [comment]
Fixed in [48b9645](https://github.com/fritzsedlazeck/Sniffles/commit/48b9645c367e928d41556d2e2d582a358ab31918)
