### ISSUE TITLE
Can't run _any_ version > 2.2 without an Exception. 

### ISSUE THREAD

**Issue by yfarjoun** [fritzsedlazeck/Sniffles#498]
Hi,

I've been running 2.2 with no problems and have been trying to upgrade to 2.3 / 2.4. I've tried various things:
- installing from conda 
- installing python in conda, and then pip for sniffles.
- installing python in conda, cloneing the git repo and installing the local code with pip

All three methods end with the same failure: when I run the code on my hifi-bam, it blows up with an error:
```
2024-07-18 18:46:40,098 INFO sniffles.main (37205): Analyzing 49282 alignments total...
2024-07-18 18:46:40,098 INFO sniffles.main (37205): 
2024-07-18 18:46:40,098 INFO sniffles.worker (37205): Starting worker 0
2024-07-18 18:46:40,107 ERROR sniffles.main (37205): Unhandled error while running sniffles.
Traceback (most recent call last):
  File "/Users/yossifarjoun/micromamba/envs/test_sniffles/bin/sniffles", line 524, in <module>
    Sniffles2_Main(processes)
  File "/Users/yossifarjoun/micromamba/envs/test_sniffles/bin/sniffles", line 443, in Sniffles2_Main
    p.start()
  File "/Users/yossifarjoun/micromamba/envs/test_sniffles/lib/python3.10/site-packages/sniffles/parallel.py", line 492, in start
    self.process.start()
  File "/Users/yossifarjoun/micromamba/envs/test_sniffles/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/yossifarjoun/micromamba/envs/test_sniffles/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/yossifarjoun/micromamba/envs/test_sniffles/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/Users/yossifarjoun/micromamba/envs/test_sniffles/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/yossifarjoun/micromamba/envs/test_sniffles/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/yossifarjoun/micromamba/envs/test_sniffles/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/yossifarjoun/micromamba/envs/test_sniffles/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_thread.RLock' object
```

 I guess I'm doing something wrong, but I'm not sure what! 

the commandline was:
```
sniffles --input sample.hifi.sorted.bam --vcf sample.vcf --reference GCA_000001405.15_GRCh38_no_alt_analysis_set.fa
```

**Comment by hermannromanek** [comment]
Hi @yfarjoun ,

Are you attempting to run sniffles on Mac?

Thanks,
Hermann

**Comment by yfarjoun** [comment]
Indeed. but I tried both native and the intel emulation (via rosetta)

Is this not supported? is there a workaround?

**Comment by yfarjoun** [comment]
but I seem to have found a solution. I'll be submitting a PR soon.

**Comment by yfarjoun** [comment]
hello @hermannromanek do you think that my PR could be reviewed? it seems to not be possible to run sniffles on OSx without it.

**Comment by hermannromanek** [comment]
Hi @yfarjoun 

Yes - thanks for the PR and for testing on Mac. It's pretty much the same as https://github.com/fritzsedlazeck/Sniffles/commits/issue490-sniffles-on-mac, so it should be no problem merging it. Out of curiosity, were there any specific concerns to limit it to darwin?

Thanks,
Hermann

**Comment by yfarjoun** [comment]
thanks for the merge @hermannromanek. I limited it to Darwin because it works on linux (if it ain't broke and all that) and I don't have access to a windows machine and so would not be able to test it...if someone else wants to do that, I am not aware of a reason not to.
